workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    instance_type: macos_instance
    environment:
      xcode: latest
    scripts:
      - name: Configure git to use token
        script: |
          git remote set-url origin https://$GITHUB_TOKEN@github.com/MiBBQ1/CopenhagenHistoryQuiz.git
      - name: Install CocoaPods dependencies
        script: |
          pod install --project-directory=CopenhagenHistoryQuiz
      - name: Build the app
        script: |
          xcodebuild -workspace CopenhagenHistoryQuiz/CopenhagenHistoryQuiz.xcworkspace -scheme CopenhagenHistoryQuiz -configuration Release build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    artifacts:
      - build/ios/Release-iphoneos/*.app
      - build/ios/Release-iphoneos/*.ipa
    publishing:
      scripts:
        - name: Publish to App Store
          script: |
            xcrun altool --upload-app -f build/ios/Release-iphoneos/CopenhagenHistoryQuiz.ipa -t ios --apiKey $APP_STORE_CONNECT_API_KEY --apiIssuer $APP_STORE_CONNECT_API_ISSUER --apiKey $APP_STORE_CONNECT_API_PRIVATE_KEY
